<a href="https://colab.research.google.com/github/AanchalDogra/classes_in_python/blob/master/Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: import numpy and pandas , create one list and one numpy array

import numpy as np
import pandas as pd

# Create a list
my_list = [1, 2, 3, 4, 5]

# Create a numpy array
my_array = np.array(my_list)


In [3]:
my_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
my_array*2

array([ 2,  4,  6,  8, 10])

In [6]:
my_array.shape

(5,)

In [7]:
np.arange(1,5)

array([1, 2, 3, 4])

In [9]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])